var text_choices = {
  "593": ["Film", "Museum", "Fairy tale", "Dance", "Clothing", "Pacific Ocean", "Number", "Aristotle", "Insect", "Hunting", "Knife"],
  "145443": ["Drawing", "Fashion", "Novel", "Pop music", "Sport", "South Africa", "Algebra", "Julius Caesar", "Climate change", "Political party", "Satellite"],
  "15613": ["Classical music", "Drawing", "Poetry", "Abstract art", "Bread", "Europe", "Prime number", "Walt Disney", "Mercury", "Psychology", "Engineering"],
  "18963870": ["Novel", "Painting", "Opera", "Folk music", "Adult", "Mountain", "Infinity", "Ferdinand Magellan", "Planet", "Money", "Car"],
  "20913771": ["Opera", "Film", "Poetry", "Singing", "Rice", "Amazon River", "Triangle", "Albert Einstein", "Gravity", "Fishing", "Camera"],
  "18949461": ["Novel", "Design", "Opera", "Rock music", "Spice", "Rome", "Line", "Sigmund Freud", "Asteroid", "Government", "Computer"],
  "15739": ["Clothing", "Woman", "Toy", "Rice", "Rock music", "Island", "Calculus", "Leonardo da Vinci", "Earthquake", "Police", "Electricity"],
  "83859": ["Child", "Home", "Man", "Coffee", "Architecture", "Atlantic Ocean", "Number", "Ludwig van Beethoven", "Earth", "Government", "Wheel"],
  "17157119": ["Family", "Clothing", "Woman", "Sugar", "Dance", "Himalayas", "Infinity", "Joan of Arc", "Big Bang", "Economics", "Internet"],
  "981": ["Desert", "Indian Ocean", "France", "Caribbean", "Museum", "Bread", "Infinity", "George Washington", "Atom", "War", "Cotton"],
  "689": ["Europe", "Mountain", "Pacific Ocean", "Germany", "Piano", "Olympic Games", "Prime number", "Nelson Mandela", "Human", "Psychology", "Ship"],
  "3383": ["India", "Desert", "Great Barrier Reef", "Africa", "Opera", "Swimming", "Calculus", "Plato", "Brain", "Capitalism", "Internet"],
  "8087628": ["Japan", "Forest", "Amazon River", "Europe", "Film", "Clothing", "Triangle", "Mahatma Gandhi", "Venus", "United Nations", "Telescope"],
  "26667": ["China", "Island", "Mediterranean Sea", "Caribbean", "Design", "Wheat", "Equation", "Socrates", "Sleep", "News", "Nuclear weapon"],
  "17867": ["New York City", "Himalayas", "Nile", "Africa", "Photography", "Sport", "Circle", "The Beatles", "Cell", "Economics", "Car"],
  "55313": ["Common cold", "Hospital", "Nutrition", "Vaccine", "Pottery", "Furniture", "Great Barrier Reef", "Marco Polo", "Physics", "Education", "Telephone"],
  "44905": ["Common cold", "Surgery", "Exercise", "Vaccine", "Fashion", "Meat", "Atlantic Ocean", "Isaac Newton", "Dinosaur", "Money", "Electricity"],
  "19572217": ["Infection", "Nutrition", "Hygiene", "Vaccine", "Novel", "Coffee", "Pacific Ocean", "Leonardo da Vinci", "Planet", "Hunting", "Camera"],
  "180121": ["Vaccine", "Nursing", "Injury", "Exercise", "Pop music", "Rice", "Sahara", "George Washington", "Organism", "Trade", "Radio"],
  "18831": ["Algebra", "Circle", "Infinity", "Prime number", "Pop music", "Bread", "Desert", "Leonardo da Vinci", "Plant", "Education", "Petroleum"],
  "22934": ["Infinity", "Triangle", "Real number", "Variable", "Classical music", "Adult", "China", "Johann Sebastian Bach", "DNA", "Law", "Car"],
  "1704824": ["Equation", "Line", "Natural number", "Arithmetic", "Poetry", "Sport", "Forest", "George Washington", "Moon", "Trade", "Refrigeration"],
  "26685": ["Calculus", "Algebra", "Number theory", "Geometry", "Piano", "Fruit", "United Kingdom", "Nelson Mandela", "Physics", "Famine", "Weapon"],
  "32897": ["Homer", "Walt Disney", "Hippocrates", "George Washington", "Singing", "Vegetable", "Africa", "Number", "Bird", "Psychology", "Television"],
  "24176": ["Leonardo da Vinci", "Henry Ford", "Albert Einstein", "Nelson Mandela", "Abstract art", "Swimming", "Germany", "Line", "Eye", "Political party", "Mobile phone"],
  "307": ["Nelson Mandela", "Alan Turing", "Plato", "Sigmund Freud", "Architecture", "Furniture", "United States", "Triangle", "Fish", "Construction", "Road"],
  "14995351": ["The Beatles", "Leonardo da Vinci", "Sigmund Freud", "Isaac Newton", "Painting", "Coffee", "Lake", "Calculus", "Physics", "Fishing", "Fossil fuel"],
  "29778": ["Albert Einstein", "Johann Sebastian Bach", "Frida Kahlo", "Elizabeth I", "Dance", "Tea", "Australia", "Algebra", "Jupiter", "Human rights", "Nuclear power"],
  "5635": ["Marco Polo", "Socrates", "Marie Curie", "Joan of Arc", "Singing", "Child", "Japan", "Geometry", "Virus", "Bank", "Internet"],
  "69880": ["George Washington", "Charlie Chaplin", "Galileo Galilei", "Socrates", "Architecture", "Milk", "Amazon rainforest", "Infinity", "Metal", "News", "Map"],
  "13692155": ["Ethics", "Religion", "Logic", "Bible", "Piano", "Board game", "Italy", "Frida Kahlo", "Star", "Mining", "Clock"],
  "24698694": ["Knowledge", "Atheism", "Belief", "Truth", "Novel", "Olympic Games", "Island", "Charlie Chaplin", "Light", "Hunting", "Coal"],
  "20062": ["Spirituality", "Free will", "Buddhism", "Religion", "Classical music", "Tea", "France", "Julius Caesar", "Physics", "Government", "Bridge"],
  "25042": ["Afterlife", "Ethics", "Christianity", "Belief", "Poetry", "Child", "Mississippi River", "Wolfgang Amadeus Mozart", "Solar System", "Business", "Glass"],
  "31880": ["Earth", "Gravity", "Carbon dioxide", "Dinosaur", "Rock music", "Wheat", "Antarctica", "Triangle", "Isaac Newton", "Law", "Firearm"],
  "14640471": ["Sun", "Atom", "Metal", "Blood", "Art", "Olympic Games", "Indian Ocean", "Number", "Albert Einstein", "Construction", "Wheel"],
  "25409": ["Tree", "Metal", "Solar System", "Light", "Architecture", "Child", "Canada", "Prime number", "Ludwig van Beethoven", "Personality", "Mobile phone"],
  "4169": ["Water", "Bird", "Jupiter", "Evolution", "Dance", "Clothing", "Island", "Infinity", "The Beatles", "Capitalism", "Ship"],
  "50482": ["Rain", "Fish", "Planet", "Eye", "Film", "Tea", "North America", "Circle", "Joan of Arc", "Bank", "Compass"],
  "37530": ["Wind", "Insect", "Venus", "Cell", "Poetry", "Bread", "River", "Line", "Galileo Galilei", "Trade", "Television"],
  "36863": ["Heart", "Carbon", "Star", "Gravity", "Painting", "Rice", "India", "Algebra", "Leonardo da Vinci", "Military", "Renewable energy"],
  "627": ["Fishing", "Famine", "Government", "United Nations", "Pottery", "Fruit", "Paris", "Number", "Charlie Chaplin", "Black hole", "Oven"],
  "183515": ["Tax", "News", "Psychology", "Education", "Architecture", "Spice", "Russia", "Equation", "Albert Einstein", "Saturn", "Computer"],
  "7959": ["Capitalism", "Human rights", "Trade", "Law", "Sculpture", "Meat", "Nile", "Prime number", "Nelson Mandela", "Bacteria", "Plastic"],
  "519280": ["Emotion", "Justice", "English language", "Mass media", "Art", "Vegetable", "Europe", "Triangle", "Isaac Newton", "Outer space", "Engine"],
  "17730": ["English language", "University", "Economics", "Government", "Architecture", "Sport", "Mountain", "Infinity", "The Beatles", "Physics", "Solar energy"],
  "19174720": ["Coal", "Wheel", "Camera", "Firearm", "Fashion", "Swimming", "Pacific Ocean", "Triangle", "Michelangelo", "Blood", "Business"],
  "37401": ["Garden", "Internet", "Weapon", "Glass", "Pop music", "Furniture", "Amazon River", "Arithmetic", "Ludwig van Beethoven", "Galaxy", "War"],
  "25676": ["Map", "Telescope", "Plastic", "Car", "Novel", "Wheat", "Europe", "Line", "Elizabeth I", "Cell", "Fishing"],
  "26301": ["Satellite", "Engine", "Dam", "Microscope", "Museum", "Coffee", "Africa", "Circle", "The Beatles", "Mammal", "Law"],
  "5623": ["Bridge", "Camera", "Ship", "Concrete", "Piano", "Man", "Vietnam", "Calculus", "Walt Disney", "Heart", "Construction"],
  "849": ["Car", "Telephone", "Wood", "Laser", "Painting", "Board game", "Himalayas", "Prime number", "Mahatma Gandhi", "Sun", "Government"],
  "1164": ["Computer", "Television", "Rail transport", "Internet", "Sculpture", "Fruit", "Sea", "Equation", "Wolfgang Amadeus Mozart", "Evolution", "Human rights"]
}